name: flutter_exif_plugin
description: A flutter plugin for reading and writing EXIF. This plugin currently only works on Android
version: 1.0.0
repository: https://github.com/spacycoder/flutter_exif
homepage: https://github.com/spacycoder/flutter_exif

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.9"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.spacycoder.flutter_exif_plugin
        pluginClass: FlutterExifPlugin
      ios:
        pluginClass: FlutterExifPlugin
