name: flutter_exif_plugin
description: A flutter plugin for reading and writing EXIF.
version: 0.0.1
author: spacycoder

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.spacycoder.flutter_exif_plugin
        pluginClass: FlutterExifPlugin
